- src/objects/api/constants.py
- src/objects/api/filters.py
- src/objects/api/utils.py
- src/objects/api/v1/openapi.yaml
- src/objects/api/v2/openapi.yaml
- src/objects/api/validators.py
- src/objects/tests/v1/test_filters.py
- src/objects/tests/v2/test_filters.py
fixes #235 
**Upd.** 
Quick performance test which shows that the performance of `data_attrs` query param with `icontains` is in line with others:
```
Name                                                          # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
GET Retrieve all objects                                         215     0(0.00%)  |     175     113     373     140  |    0.72    0.00
*GET Retrieve by data_attrs with icontains                       212     0(0.00%)  |      96      73     171      93  |    0.71    0.00
GET Retrieve by data_attrs with lte                              193     0(0.00%)  |     110 …
```
> add icontains to data_attrs operators

- docs/admin/notifications.rst
The link https://open-notificaties.readthedocs.io/en/stable/manual/subscriptions.html will work once the ON docs are deployed again (points to https://github.com/open-zaak/open-notificaties/blob/main/docs/manual/subscriptions.rst)
> :memo: Add reference to subscription docs in Open Notificaties

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Some extra functionality and bugfixes for the OpenID Connect integration, mentioned in the changelog: https://github.com/maykinmedia/mozilla-django-oidc-db/blob/master/CHANGELOG.rst
> :arrow_up: Bump mozilla-django-oidc-db to 0.7.1

- src/objects/conf/base.py
previously the `SESSION_COOKIE_NAME` for objects and objecttypes were the same, making it impossible to be logged into both apps simultaneously
> :bug: Unique name for session ID cookie

- src/objects/core/models.py
- src/objects/tests/v2/test_object_api.py
Fixes #282
Added a test case to recreate the initial problem described on issue 282
1. Create an Object with some date for startAt
2. Update this Object with a date before the startAt in step 1
3. Attempt to update this Object again, resulting in a 500 error:
`django.db.utils.IntegrityError: duplicate key value violates unique constraint "core_objectrecord_correct_id_key"
DETAIL:  Key (correct_id)=(2) already exists.`
After debugging discovered that the issue was the last_record function of the Object model.
Where we ordered on startAt and -index.
The solution to this problem was to remove the startAt from the orderBy.
> Ticket 282 updating starting at value results in 500

- src/objects/api/filter_backends.py
- src/objects/api/utils.py
- src/objects/tests/v2/test_filters.py
- src/objects/utils/serializers.py
Using a `datetime` object instead of the `date` one can result to a wrong filtering behavior in some cases.
Suppose we have a few `ObjectRecord` instances, with a date field in their data. Trying to filter on this field with a `datetime` object and a `gte`/`lte` lookup will result in the following:
```python
>>> ObjectRecord.objects.filter(
data__myDateField__gte=datetime.strptime("2000-02-20", "%Y-%m-%d")
).order_by("data__myDateField").first().data["myDateField"]
'2001-01-10"  # Not the correct object
```
Using a `date` object instead:
```python
>>> ObjectRecord.objects.filter(
data__myDateField__gte=date.fromisoformat("2000-02-20")
).order_by("data__myDateField").first().data["myDateField"]
'2000-02-00'  # gte lookup works as excepted
```
> :bug: Fix date parsing in API filtering

- src/objects/api/filter_backends.py
- src/objects/token/admin.py
- src/objects/utils/serializers.py
As `fk_name` wasn't set on `PermissionInline` (and needs to be set as the `Permission` model has multiple foreign keys), the url query parameter was incorrect when trying to add a permission from a token auth. The query parameter is now correct and the initial value on the form is set correctly
> :bug: Initial token value set on Permission admin

- docker-compose-quickstart.yml
Gezien in #313 en vanuit CI, docker-compose-quickstart start niet meer (goed) vanuit master aangezien ALLOWED_HOSTS=localhost ontbreekt.
> :rocket: ensuring docker-compose-quickstart runs

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Patch Tuesday,
When you try to install the requirements from base.txt it gives you an error. This is because an older version of the packages: **uwsgi & ruamel yaml clib**
In this pull request I updated the dependencies to the latest version, so it doesn't give you an error when installing.
> ⬆️  Upgrade pip packages

- src/objects/api/serializers.py
- src/objects/api/utils.py
- src/objects/api/v1/openapi.yaml
- src/objects/api/v1/views.py
- src/objects/api/v2/openapi.yaml
- src/objects/api/v2/views.py
- src/objects/tests/test_merge_patch.py
- src/objects/tests/v1/test_object_api.py
- src/objects/tests/v2/test_object_api.py
- src/objects/typing.py
Fixes https://github.com/maykinmedia/objects-api/issues/351
> ✨ Use JSON Merge Patch when doing a partial update on records

- src/objects/conf/base.py
Fix #321 
Not sure if we want to use `django_yubin.backends.QueuedEmailBackend` as openforms e.g.
> Add email environment variables

- docs/installation/config.rst
- src/objects/conf/base.py
> :wrench: Add config option for USE_X_FORWARDED_HOST

- Dockerfile
- bin/check_celery_worker_liveness.py
- Celery container crashes because the celery binary does not exist;
- Add `check_celery_worker_liveness.py` , we use it for healthchecks on the celery containers;
> :bug: copy celery binary

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
taiga issue: https://taiga.maykinmedia.nl/project/maykin-intranet/issue/739
closes: https://github.com/maykinmedia/objects-api/issues/386
> :heavy_plus_sign: Replace dependencies with open-api-dependencies

- docs/installation/config.rst
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/conf/base.py
- src/objects/fixtures/default_admin_index.json
Fixes #344
replacement for https://github.com/maykinmedia/objects-api/pull/345
> :heavy_plus_sign: Add django-log-outgoing-requests

- .github/workflows/quick-start.yml
- src/objects/fixtures/demodata.json
The goal of this PR to fix CI in master branch and make it green again. 
**Explanation why it is broken:**
* We have quick-start CI workflow which uses Objects API image from docker hub and fixtures inside this image
* In the PR #397 the structure of Token model was changed, but the related fixtures were not updated
* The CI was green in the PR because quick-start action uses docker image from docker hub with old Token model structure
* After the PR was merged the docker image on docker hub was updated, so now we have a docker image with 'latest' tag where demodata fixture and token model have different structures. 
* So to fix it we need to publish a new docker image with updated fixture but to do so we need green CI
* Therefore loading fixtures is temporarily disabled until the fixtures …
> :green_heart: update demodata with token model change

- src/objects/api/serializers.py
- src/objects/api/v1/openapi.yaml
- src/objects/api/v2/openapi.yaml
- src/objects/tests/v2/test_object_api.py
> fix for correctionFor = null

- src/objects/core/admin.py
- src/objects/core/models.py
- src/objects/token/admin.py
Fixes #315
**Changes**
Added some version and uuid fields in the admin panel.
> :sparkles: [#315] added extra version and uuid fields in admin

- .github/workflows/ci.yml
- .github/workflows/code-quality.yml
- Dockerfile
- INSTALL.rst
- requirements/ci.txt
- requirements/dev.txt
- src/objects/accounts/models.py
- src/objects/api/urls.py
- src/objects/api/v1/urls.py
- src/objects/api/v2/urls.py
> [#379] Make use of Python3.11

- Dockerfile
- bin/celery_worker.sh
- docker-compose.yml
- src/objects/celery.py
Fixes #424 
**Changes**
- Add celery health check (Same as open_inwoner and openforms)
> :stethoscope: add celery healthcheck

- .jshintrc
- karma.conf.js
- package-lock.json
- package.json
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/api/validators.py
- src/objects/config/objecttypes.py
- src/objects/core/models.py
- src/objects/core/utils.py
- src/objects/tests/utils.py
- src/objects/tests/v1/test_validation.py
- src/objects/tests/v2/test_validation.py
- src/objects/token/admin.py
Fixes #428 
**Changes**
Updated zgw-consumers to 0.29.0 to update more python security issues
removed gemma-zds-client functionality thoughout the project
updated insecure libraries:
- certifi
- cryptography
> :arrow_up: upgraded zgw-consumers and removed zds-client from project

- .github/workflows/ci.yml
- bin/generate_envvar_docs.sh
- docs/installation/config.rst
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/conf/base.py
- src/objects/conf/dev.py
- src/objects/templates/open_api_framework/env_config.rst
Fixes open-zaak/open-zaak#1649 partially
Requires https://github.com/maykinmedia/open-api-framework/pull/22 to be merged and released
**Changes**
* Use envvar documentation mechanism from OAf
* Add CI job to check if envvar docs were updated
>  📝 [open-zaak/open-zaak#1649] Document envvars 

- src/objects/api/constants.py
- src/objects/api/v1/filters.py
- src/objects/api/v1/openapi.yaml
- src/objects/api/v2/filters.py
- src/objects/api/v2/openapi.yaml
- src/objects/api/validators.py
- src/objects/tests/v1/test_filters.py
- src/objects/tests/v2/test_filters.py
> :sparkles:[#414] add in operator to API

- docker-compose.yml
- docs/installation/config_cli.rst
- src/objects/conf/base.py
- src/objects/tests/commands/test_setup_configuration.py
Fixes https://github.com/maykinmedia/django-setup-configuration/issues/10 (Objects API part)
> disable configuration steps by default

- .github/workflows/oaf-check.yml
fixes: maykinmedia/open-api-framework#44
> Add github action to check if OAF is Up to Date

- src/objects/token/admin.py
- src/objects/token/tests/cassettes/PermissionAdminTests.test_with_object_types_api_v1.yaml
- src/objects/token/tests/cassettes/PermissionAdminTests.test_with_object_types_api_v2.yaml
- src/objects/token/tests/test_admin.py
Fixes #449
Supports paginated response from OT V2
> :bug:[#449] support objecttypes API with pagination

- .github/workflows/oaf-check.yml
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Fixes maykinmedia/open-api-framework#44
> :construction_worker: check OAF version on PRs

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/conf/base.py
- src/objects/core/tests/factories.py
- src/objects/fixtures/demodata.json
- src/objects/tests/commands/test_setup_configuration.py
- src/objects/tests/v2/test_notifications_kanaal.py
- src/objects/utils/client.py
fixes https://github.com/maykinmedia/open-api-framework/issues/66
depends on https://github.com/maykinmedia/commonground-api-common/pull/45
> bump zgw-consumers to 0.35.1, commonground-api-common to 2.0.1, OAF to 0.9.0

- docker/setup_configuration/data.yaml
- docs/installation/config_cli.rst
- src/objects/conf/base.py
- src/objects/core/models.py
- src/objects/core/tests/files/objecttypes_empty_database.yaml
- src/objects/core/tests/files/objecttypes_existing_objecttype.yaml
- src/objects/core/tests/files/objecttypes_idempotent.yaml
- src/objects/core/tests/files/objecttypes_invalid_uuid.yaml
- src/objects/core/tests/files/objecttypes_unknown_service.yaml
- src/objects/core/tests/test_objecttype_config.py
- src/objects/setup_configuration/models/objecttypes.py
- src/objects/setup_configuration/steps/objecttypes.py
Fixes #467 
**Changes**
Allows the configuration of `Service`'s with django-setup-configuration to setup a connection with objecttype(s)
> [#467] Setup objecttypes through django-setup-configuration

- bin/setup_configuration.sh
- docker/setup_configuration/data.yaml
- docs/installation/config_cli.rst
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/conf/base.py
Fixes #483 
**Changes**
Includes changes necessary to configure mozilla-django-oidc-db through django-setup-configuration.
~Edit: This branch was based on `feature/467-objecttypes-setup-config` as that includes some changes to the setup configuration structure~
> [#483] add support for mozilla django OIDC db config

- .github/workflows/oas-check.yml
- src/objects/api/v2/filters.py
- src/objects/api/v2/openapi.yaml
- src/objects/api/v2/views.py
- src/objects/api/validators.py
- src/objects/tests/v2/test_filters.py
- src/objects/utils/filters.py
Fixes #472 
We use comma as a separator between `data_attrs` values
If we want to support commas inside values we can consider several options:
1. Remove several value groups, separated by commas, so comma won't be a reserved character here
Before: `?data_attrs=naam__icontains__anna,naam__icontains__Advies` 
After:`?data_attrs=naam__icontains__anna&data_attrs=naam__icontains__Advies, support`
This is my personal favorite option, but it will break current API
2. Change separator from comma to other character, for example to `|`. 
Before: `?data_attrs=naam__icontains__anna,naam__icontains__Advies` 
After: `?data_attrs=naam__icontains__anna|naam__icontains__Advies, support` 
Also a nice option, but also breaks current API
3. Escape comma in the value part or use other char instead of comma …
> support commas in data_attrs query param

- .github/workflows/ci.yml
this version fixes publishing latest docker tag
Fixes #504
> :construction_worker: [#504] Pin to v3.0.1 of publish workflow

- .github/ISSUE_TEMPLATE/prepare-release.md
Fixes maykinmedia/open-api-framework#107 partially
**Changes**
* Add prepare release template
> :memo: [maykinmedia/open-api-framework#107] Add prepare release template

- .bumpversion.cfg
- .github/ISSUE_TEMPLATE/prepare-release.md
- bin/bump-my-version.sh
- requirements/dev.in
- requirements/dev.txt
Fixes maykinmedia/open-api-framework#107 partially
**Changes**
* Add bump-my-version to dev dependencies
> :heavy_plus_sign: Add bump-my-version to dev dependencies

- docs/installation/config.rst
- src/objects/conf/base.py
- src/objects/utils/autoschema.py
> :bug: update settings and imports after updating OAF

- .github/workflows/ci.yml
- .readthedocs.yaml
- docs/conf.py
- docs/installation/config_cli.rst
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/api/kanalen.py
- src/objects/core/tests/test_objecttype_config.py
- src/objects/setup_configuration/models/token_auth.py
- src/objects/setup_configuration/steps/objecttypes.py
- src/objects/setup_configuration/steps/token_auth.py
- src/objects/setup_configuration/tests/test_token_auth_config.py
Fixes #521
**Changes**
* Update docs for setup-config
>  📝 [#521] Update docs for setup-config

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
> :arrow_up: bump django to 4.2.19, cryptography to 44.0.1

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- docs/api/index.rst
- docs/changelog.rst
- docs/conf.py
- docs/index.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/objects/__init__.py
> :bookmark: release 3.0.1

- src/objects/js/components/admin/permissions/permission-form.js
- src/objects/js/components/forms/inputs.js
> [#523] Added help_text in Change Permission View

- .github/workflows/ci.yml
- performance_test/conftest.py
- performance_test/create_data.py
- performance_test/test_objects_list.py
- requirements/ci.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/test-tools.in
- src/objects/conf/dev.py
- src/objects/core/query.py
- src/objects/tests/v2/test_object_api.py
- src/objects/urls.py
Fixes #538 
Reduces the response time of `GET /api/v2/objects` from about ~8.6s to ~0.26s (for a query that returns 5000 objects)
**Changes**
* Add django-silk for performance profiling
* Optimize objects list performance
* Add basic performance tests with pytest-benchmark
Failing performance test before the changes: https://github.com/maykinmedia/objects-api/actions/runs/13653707936/job/38167868135
> ⚡ [#538] Optimize objects list performance

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Fixes #543 partially
**Changes**
* Upgrade jinja2 to 3.1.6 to fix security issue
> :arrow_up: Upgrade jinja2 to 3.1.6 to fix security issue

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
since Celery 5.5 isn't out yet, this should fix the redis connection issues
Fixes #541
**Changes**
* Upgrade kombu to 5.4.2
> :arrow_up: [#541] Upgrade kombu to 5.4.2

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- docs/api/index.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/objects/__init__.py
Fixes #543 
**Changes**
* Release version 3.0.2
>  🔖 [#543] Release version 3.0.2

- .github/workflows/oas-check.yml
- bin/generate_schema.sh
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/api/v2/openapi.yaml
- src/objects/utils/apps.py
to verify that the schema is up to date
Fixes maykinmedia/open-api-framework#115 partially
**Changes**
* Always run OAS check
> :construction_worker: [maykinmedia/open-api-framework#115] Always run OAS check

- docs/installation/config.rst
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/conf/api.py
- src/objects/conf/base.py
- src/objects/tests/v2/test_notifications_kanaal.py
- src/objects/utils/__init__.py
Partially fixed https://github.com/maykinmedia/open-api-framework/issues/59
> :sparkles: Remove django.contrib.sites

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Upgrade `commonground-api-common`
> :arrow_up: [maykinmedia/open-klant#341] Upgrade commonground-api-common

- src/objects/tests/admin/test_token_permissions.py
- src/objects/token/admin.py
> :bug: [#374] Fix: Token auth select is empty when creating a permission

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- docs/api/index.rst
- package-lock.json
- package.json
- publiccode.yaml
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/__init__.py
Fixes #574 
**Changes**
- prepare 3.0.4
> 🔖 [#574] Release version 3.0.4

- docs/api/compliancy/api-strategy.rst
because VNG has stopped supporting it, see https://standaarden.vng.nl/APItestplatform
> :memo: Remove references to API test platform

- src/objects/api/v2/openapi.yaml
- src/objects/utils/apps.py
- src/objects/utils/fields.py
Fixes #576 
**Changes**
- Overrides the serializer_field_mapping for models.JSONField
- inspired/copied from [rest-framework-gis](https://github.com/openwisp/django-rest-framework-gis/blob/master/rest_framework_gis/apps.py)
- rest-framework-gis is also the reason that setting the mapping in a mixin is not possible:
```py
class JsonObjectFieldModelSerializerMixin:
serializer_field_mapping = (
serializers.ModelSerializer.serializer_field_mapping.copy()
)
serializer_field_mapping[models.JSONField] = JSONObjectField
```
> 🐛 [#576] fix invalid data field type in api spec

- Dockerfile
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Fixes #562 
**Changes:**
* Run apt-get update in Dockerfile
* Upgrade tornado to 6.5.0 to fix security issues
> :arrow_up: Fix security issues

- docker-compose.yml
- docker/docker-compose.observability.yaml
- docker/objecttypes/objecttypes.json
- docker/observability/README.md
- docker/observability/promtail/config.yml
- docker/setup_configuration/data.yaml
- docker/setup_configuration/objecttypes_data.yaml
promtail to scrape logs, loki to store them and grafana to visualize them
Fixes #591
Based on #594, so that should be merged first
**Changes**
* Add local setup for observability
* Add objecttypes service with fixture to docker-compose.yml
> :whale: [#591] Add local setup for observability

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/api/v2/views.py
- src/objects/conf/api.py
- src/objects/utils/oas_extensions/query.py
Fixes maykinmedia/open-klant#414
**Changes**
Changed default filter backend and used commonground-api-common branch:
https://github.com/maykinmedia/commonground-api-common/pull/94
> :bug: changed default backend

- docker/observability/README.md
- docs/conf.py
- docs/index.rst
- docs/manual/index.rst
- docs/manual/logging.rst
- src/objects/setup_configuration/steps/token_auth.py
Fixes #593 
**Changes**
* Add documentation for logging and log event types
> :memo: [#593] Add documentation for logging and log event types

- .github/workflows/code-quality.yml
- ruff.toml
- src/objects/celery.py
- src/objects/utils/middleware.py
Fixes #587
**Changes**
Added rule to ban the logging import
> :wrench: [#587] added rule to ban import logging

- src/objects/scss/admin/_admin_theme.scss
- src/objects/scss/admin/_app_overrides.scss
- src/objects/scss/admin/_vars.scss
- src/objects/scss/admin/themes/_dark.scss
- src/objects/scss/admin/themes/_light.scss
- src/objects/templates/admin/base_site.html
Fixes #https://github.com/maykinmedia/open-api-framework/issues/149
**Changes**
Fixed light/dark theme in admin UI with the missing toggle.
> :lipstick: Fix light/dark themes for admin

- docs/manual/logging.rst
Fixes #639 
**Changes**
Add Objecttypes logging docs
> :memo: [#639] add Objecttypes logging docs

- docs/installation/config.rst
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/objects/celery.py
- src/objects/conf/base.py
- src/objects/conf/dev.py
- src/objects/conf/production.py
:arrow_up: Bump `commonground-api-common` to 2.10.0
- Update related to this issue [maykinmedia/open-api-framework#175]: added an exception logging event that includes code, status, and the invalidParams message.
:arrow_up: Bump `open-api-framework` to 0.13.0
> :arrow_up: Upgrade dependencies

- src/objects/tests/v2/test_filters.py
- src/objects/utils/views.py
Fixes https://github.com/maykinmedia/open-api-framework/issues/175
- Added structlog event for API `HTTP_400_BAD_REQUEST` exceptions
- Fixed error for generic error / exceptions message instead 500 page error
> :recycle: [maykinmedia/open-api-framework#175] Improve handled_exception
