maykinmedia/objects-api

.travis.yml
package-lock.json
package.json
requirements/dev.txt
src/objects/conf/ci.py

Set up Travis

---

.travis.yml
Dockerfile
bin/docker_push.sh

Fixes https://github.com/maykinmedia/objects-api/issues/43

push docker image via travis

---

.bumpversion.cfg
appstore.yaml
publiccode.yaml

Added publiccode

---

bin/generate_demo_fixture.sh
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/objects/conf/base.py
src/objects/fixtures/demodata.json

Updated demo data

---

requirements/base.in
requirements/dev.txt
src/objects/api/serializers.py
src/objects/core/admin.py
src/objects/core/models.py
src/objects/core/query.py
src/objects/core/utils.py
src/objects/tests/schemas/objecttypes.yaml
src/objects/tests/test_object_api.py
src/objects/tests/test_validation.py
src/objects/tests/utils.py
src/openapi.yaml

Several fixes and improvements

---

src/objects/api/validators.py
src/objects/tests/test_filters.py

fixes https://github.com/maykinmedia/objects-api/issues/123

filter with invalid data_attrs param

---

src/objects/api/schema.py
src/objects/api/views.py
src/openapi.yaml

Added API-docs about mostly history.

Updated API doc.

---

README.NL.rst
README.rst

Corrected docs link.

---

src/objects/core/admin.py

Added filtering objects by objecttype

---

docs/api/compliancy/api-strategy.rst
docs/api/index.rst
docs/api/usage.rst

add usage examples for O & O APIs

---

src/objects/api/serializers.py
src/objects/core/admin.py
src/objects/tests/test_object_api.py
src/objects/tests/test_validation.py
src/openapi.yaml

Feature/admin add UUID

---

docs/api/compliancy/api-strategy.rst
src/objects/api/serializers.py
src/objects/conf/api.py
src/objects/tests/test_object_api_fields.py
src/objects/utils/autoschema.py
src/objects/utils/serializers.py
src/openapi.yaml

fields in query params

---

src/objects/core/migrations/0022_move_object_types_to_separate_model.py

sentry issue - https://sentry.maykinmedia.nl/maykin-media/objecttypes-utrecht-test-mp/issues/282887/?query=is%3Aunresolved

:bug: catch ValueError in data migration

---

src/objects/tests/test_stuf.py

rework material and formal history

---

docs/api/usage.rst
src/objects/api/filters.py
src/objects/api/schema.py
src/objects/core/query.py
src/openapi.yaml

swap material and formal history in documentation

---

src/objects/conf/api.py
src/openapi.yaml

:memo: make read-only fields non-required in OAS

---

README.rst
docs/api/postman.rst
docs/api/usage.rst
docs/index.rst
docs/installation/config.rst
docs/installation/deployment/index.rst
docs/installation/quickstart.rst
docs/introduction/background.rst
docs/introduction/definitions.rst
docs/introduction/index.rst
docs/introduction/information-model.rst
docs/introduction/team.rst
docs/introduction/vision.rst
docs/introduction/visualization.rst

Based on a full read, I've made the following changes:
- Increased readability by removing unnecessary duplication (i.e. Occam's razor)
- Fixed minor typos.
- Adjusted formatting on certain parts.
- Added instructions for Postman collections.

📝 Update documentation.

---

src/objects/conf/base.py

fixes https://github.com/maykinmedia/objects-api/issues/237

add env var to switch off notifications

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/objects/conf/base.py
src/objects/templates/admin/base_site.html
src/objects/utils/admin_index.py

add 2fa support

---

docs/installation/config.rst
src/objects/conf/base.py
src/objects/conf/ci.py
src/objects/templates/admin/base_site.html

fixes: https://github.com/maykinmedia/objects-api/issues/250
I ran into this issue when adding OIDC for the admin (request from Den Haag)

:wrench: Add environment vars to disable admin 2FA

---

src/objects/api/fields.py
src/objects/api/filter_backends.py
src/objects/api/kanalen.py
src/objects/api/mixins.py
src/objects/api/serializers.py
src/objects/api/v1/filters.py
src/objects/api/v1/openapi.yaml
src/objects/api/v1/urls.py
src/objects/api/v1/views.py
src/objects/api/v2/filters.py
src/objects/api/v2/openapi.yaml
src/objects/api/v2/urls.py
src/objects/api/v2/views.py
src/objects/api/validators.py
src/objects/core/query.py
src/objects/tests/v1/test_notifications_send.py
src/objects/tests/v2/test_filters.py
src/objects/tests/v2/test_notifications_send.py
src/objects/tests/v2/test_ordering.py
src/objects/token/permissions.py
src/objects/utils/autoschema.py
src/objects/utils/oas_extensions/fields.py
src/objects/utils/oas_extensions/query.py
src/objects/utils/serializers.py

add ordering with refactor

---

src/objects/conf/base.py

:bug: [#287] Read NOTIFICATIONS_DISABLED setting from environment as boolean

---

docs/installation/config.rst
src/objects/conf/base.py

previously, MIDDLEWARE and INSTALLED_APPS were not updated, so the integration did not work

:bug: Fix Elastic APM configuration

---

src/objects/js/components/index.js
src/objects/js/components/nav/index.js
src/objects/sass/_app.scss
src/objects/sass/_fonts.scss
src/objects/sass/_vars.scss
src/objects/sass/components/_all.scss
src/objects/sass/components/_button.scss
src/objects/sass/components/_container.scss
src/objects/sass/components/_footer.scss
src/objects/sass/components/_link.scss
src/objects/sass/components/_nav.scss
src/objects/sass/components/_title.scss
src/objects/sass/screen.scss
src/objects/templates/index.html
src/objects/templates/master.html

replace boostrap styles with custom css

---

src/objects/conf/local_example.py

Use the correct postgis engine database.

:wrench: Fix database engine in `local_example.py`

---

CONTRIBUTING.md
setup.cfg
src/objects/accounts/models.py
src/objects/api/constants.py
src/objects/api/fields.py
src/objects/api/filter_backends.py
src/objects/api/serializers.py
src/objects/api/v1/filters.py
src/objects/api/v2/filters.py
src/objects/api/v2/openapi.yaml
src/objects/api/validators.py
src/objects/core/models.py
src/objects/tests/v2/test_filters.py
src/objects/token/authentication.py
src/objects/token/constants.py
src/objects/token/management/commands/generate_token.py
src/objects/token/models.py
src/objects/utils/autoschema.py
src/objects/utils/filters.py
src/objects/utils/serializers.py

[#306] Add `typeVersion` filter to `ObjectRecordQueryset`

---

docs/installation/config.rst
src/objects/conf/base.py
src/objects/conf/ci.py
src/objects/conf/dev.py
src/objects/conf/docker.py
src/objects/conf/tests/test_config_helper.py
src/objects/conf/utils.py

Environment config for Sentry

---

.github/workflows/ci.yml
.github/workflows/quick-start.yml
docker-compose-quickstart.yml

[#334] main branch groen

---

src/objects/conf/base.py

to fix crashing OIDC config page

:bug: Add django_jsonform to INSTALLED_APPS

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
docs/api/index.rst
package-lock.json
package.json
publiccode.yaml
src/objects/__init__.py
src/objects/api/v2/openapi.yaml
src/objects/conf/api.py

(Don't mind the wrong branch name)

🔖 Release 2.3.0

---

src/objects/conf/base.py

Since we now need to deploy redis anyway for celery.

:wrench: Add missing cache settings

---

src/objects/scss/admin/_app_overrides.scss

:lipstick:[#392] fix styling of OIDC login

---

src/objects/tests/v2/test_jsonschema.py

:white_check_mark: [#330] add tests with 'additionalProperties'

---

src/objects/api/validators.py
src/objects/tests/v2/test_validation.py

save objects with empty data

---

src/objects/scss/admin/_admin_theme.scss

Fixes https://github.com/open-zaak/open-notificaties/issues/150 (Objects API part)

:lipstick: fix help-text icon layout in the admin

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
docs/api/index.rst
package-lock.json
package.json
publiccode.yaml
src/objects/__init__.py
src/objects/api/v2/openapi.yaml
src/objects/conf/api.py

:bookmark: release 2.4.0

---

src/objects/api/v2/views.py
src/objects/tests/v2/test_object_api.py

:bug: [#329] paginate object_history endpoint

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
docs/api/index.rst
package-lock.json
package.json
publiccode.yaml
src/objects/__init__.py
src/objects/api/v2/openapi.yaml
src/objects/conf/api.py

Fixes https://github.com/maykinmedia/objects-api/issues/436 (Objects API part)

:bookmark: release 2.4.2

---

Dockerfile
package-lock.json

Fixes #50
**Changes**
Updated setuptools version is in Dockerfile
fixed npm vulnerabilities

:arrow_up: [#50] updated setuptools in Dockerfile, fixed npm vulnerabilities

---

bin/docker_start.sh

Fixes Utrecht 277 and others, to ensure we have sane defaults it's better to ensure our uwsgi default settings are more workable for production setups

Increase uwsgi concurrency

---

src/objects/conf/api.py

Fixes open-zaak/open-zaak#1780 partially
**Changes**
* Fix setting NOTIFICATIONS_DISABLED via envvar

:bug: [open-zaak/open-zaak#1780] Fix setting NOTIFICATIONS_DISABLED via envvar

---

docs/installation/config.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/objects/conf/api.py

Fixes maykinmedia/open-api-framework#68
Also fixes:  maykinmedia/mozilla-django-oidc-db#116

:wrench:[maykinmedia/open-api-framework#68] fix CSP errors

---

.github/workflows/ci.yml

Partially fixes https://github.com/maykinmedia/objects-api/issues/463

Disable trivy image scan

---

docs/admin/notifications.rst

Fixes #403 
**Changes**
* Document Notificaties API retry behavior

:memo: [#403] Document Notificaties API retry behavior

---

src/objects/api/serializers.py
src/objects/api/validators.py
src/objects/tests/v2/test_object_api.py

fix validation for merge PATCH

---

package-lock.json
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes the current security alerts 
**Changes**
Updates python requirements & npm dependencies

Security updates

---

.github/workflows/quick-start.yml
docker/setup_configuration/data.yaml

Fixes maykinmedia/objects-api#509
**Changes**
* Use correct branch in quickstart job

:green_heart: [maykinmedia/objects-api#509] Use correct branch in quickstart job

---

src/objects/urls.py

Fixes: https://github.com/maykinmedia/open-api-framework/issues/79
**Changes**
disables the admin nav sidebar

[maykinmedia/open-api-framework#79] disable admin nav sidebar

---

src/objects/tests/v2/test_validation.py

:bug: [#550] Fix tests

---

CHANGELOG.rst
docs/api/compliancy/vng.rst
docs/api/performance.rst

and fix other docs build errors in changelog
Fixes #599
**Changes**
* Fix incorrect formatting for tables in docs

:memo: [#599] Fix incorrect formatting for tables in docs

---

src/objects/api/v2/filters.py
src/objects/core/admin.py
src/objects/core/tests/test_admin.py

Fixes #615
**Changes**
* Avoid n+1 queries for Services in Objects admin

:zap: [#615] Avoid n+1 queries for Services in Objects admin

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Should improve performance
Before: https://github.com/maykinmedia/objects-api/actions/runs/15823616745/job/44598307915#step:5:657
After: https://github.com/maykinmedia/objects-api/actions/runs/16044659986/job/45273015012?pr=630#step:5:664

:arrow_up: Upgrade OAF to add psycopg[binary]

---

CHANGELOG.rst
README.NL.rst
README.rst
docs/api/index.rst
package-lock.json
package.json
publiccode.yaml
pyproject.toml
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/objects/__init__.py

:bookmark: Release 3.1.1

---

docker-compose.yml
docs/installation/config.rst
src/objects/conf/base.py
src/objects/conf/docker.py

**Changes**
* Fix incorrect default in docs for DB_CONN_MAX_AGE

:memo: Fix incorrect default in docs for DB_CONN_MAX_AGE

---

docker-compose.yml
docs/installation/config.rst
src/objects/celery.py
src/objects/conf/base.py

:wrench: [#643] Expose Celery result_expires

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/objects/fixtures/demodata.json

Fixes maykinmedia/open-api-framework#172
**Changes**

⬆️ [maykinmedia/open-api-framework#172] Upgrade zgw-consumers to 1.0.0

---

src/objects/conf/base.py
src/objects/setup.py

Fixes maykinmedia/open-api-framework#179
**Changes**

 :sparkles: [maykinmedia/open-api-framework#179] Monkeypatch requests to set default timeout

---

CHANGELOG.rst
README.NL.rst
README.rst
docs/api/index.rst
docs/introduction/uml-diagram.rst
package-lock.json
package.json
publiccode.yaml
pyproject.toml
src/objects/__init__.py

Fixes https://github.com/maykinmedia/objects-api/issues/655

:bookmark: Release 3.1.4

---

bin/docker_start.sh

Fixes maykinmedia/open-api-framework#85
**Changes**

:sparkles: [maykinmedia/open-api-framework#85] Increase uwsgi and celery worker numbers

---

.github/workflows/ci.yml
CHANGELOG.rst
README.NL.rst
README.rst
docs/api/index.rst
package-lock.json
package.json
publiccode.yaml
pyproject.toml
src/objects/__init__.py

Fixes #664 
**Changes**
* Release version 3.2.0

:bookmark: [#664] Release version 3.2.0
